# Generated by Django 4.2.27 on 2026-04-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CourseRegistration',
        ),
    ]
